In [1]:
import pandas as pd
df = pd.read_csv('/home/mo/Desktop/electrical_fault_detection/datasets/classData.xls')

In [2]:
X = df[['Ia','Ib','Ic','Va','Vb','Vc']]
X

              Ia          Ib          Ic        Va        Vb        Vc
0    -151.291812   -9.677452   85.800162  0.400750 -0.132935 -0.267815
1    -336.186183  -76.283262   18.328897  0.312732 -0.123633 -0.189099
2    -502.891583 -174.648023  -80.924663  0.265728 -0.114301 -0.151428
3    -593.941905 -217.703359 -124.891924  0.235511 -0.104940 -0.130570
4    -643.663617 -224.159427 -132.282815  0.209537 -0.095554 -0.113983
...          ...         ...         ...       ...       ...       ...
7856  -66.237921   38.457041   24.912239  0.094421 -0.552019  0.457598
7857  -65.849493   37.465454   25.515675  0.103778 -0.555186  0.451407
7858  -65.446698   36.472055   26.106554  0.113107 -0.558211  0.445104
7859  -65.029633   35.477088   26.684731  0.122404 -0.561094  0.438690
7860  -64.598401   34.480799   27.250065  0.131669 -0.563835  0.432166

[7861 rows x 6 columns]

In [3]:
y=df[['G','C','B','A']]
y

      G  C  B  A
0     1  0  0  1
1     1  0  0  1
2     1  0  0  1
3     1  0  0  1
4     1  0  0  1
...  .. .. .. ..
7856  0  0  0  0
7857  0  0  0  0
7858  0  0  0  0
7859  0  0  0  0
7860  0  0  0  0

[7861 rows x 4 columns]

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.multioutput import MultiOutputClassifier
from xgboost import XGBClassifier

In [5]:
#split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
#model 1 : Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [7]:

y_pred_rf = rf_model.predict(X_test)
print('random forest classifier classification report:\n', classification_report(y_test, y_pred_rf))

random forest classifier classification report:
               precision    recall  f1-score   support

           0       0.88      0.86      0.87       691
           1       1.00      1.00      1.00       611
           2       1.00      1.00      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       0.97      0.97      0.97      3041
   macro avg       0.97      0.97      0.97      3041
weighted avg       0.97      0.97      0.97      3041
 samples avg       0.68      0.68      0.68      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [8]:
#model 2 : XGBoost Classifier
# --- Model 2: XGBoost (Multi-Output Wrapped) ---
xgb_base = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
xgb = MultiOutputClassifier(xgb_base)
xgb.fit(X_train, y_train)

MultiOutputClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=None,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=True,
                                              eval_metric=None,
                                              feature_types=None,
                                              feature_weights=None, gamma=None,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=0.1, max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None, max_depth=6,
                                              max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=100, n_jobs=None,
                                              num_parallel_tree=None, ...))

In [9]:
y_pred_xgb = xgb.predict(X_test)
print('XGBoost classifier classification report:\n', classification_report(y_test, y_pred_xgb))

XGBoost classifier classification report:
               precision    recall  f1-score   support

           0       0.81      0.83      0.82       691
           1       1.00      1.00      1.00       611
           2       1.00      1.00      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       0.96      0.96      0.96      3041
   macro avg       0.95      0.96      0.95      3041
weighted avg       0.96      0.96      0.96      3041
 samples avg       0.67      0.67      0.67      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [10]:
# --- Model 3: Voting Classifier (Decision Tree + k-NN + Naive Bayes) ---
dt = DecisionTreeClassifier(random_state=42)
knn = KNeighborsClassifier(n_neighbors=5)
gnb = GaussianNB()

voting_base = VotingClassifier(
    estimators=[('dt', dt), ('knn', knn), ('gnb', gnb)],
    voting='hard'
)
voting = MultiOutputClassifier(voting_base)
voting.fit(X_train, y_train)

MultiOutputClassifier(estimator=VotingClassifier(estimators=[('dt',
                                                              DecisionTreeClassifier(random_state=42)),
                                                             ('knn',
                                                              KNeighborsClassifier()),
                                                             ('gnb',
                                                              GaussianNB())]))

In [11]:

y_pred_voting = voting.predict(X_test)
print('Voting classifier classification report:\n', classification_report(y_test, y_pred_voting))

Voting classifier classification report:
               precision    recall  f1-score   support

           0       0.81      0.91      0.86       691
           1       1.00      0.98      0.99       611
           2       1.00      0.97      0.99       849
           3       1.00      1.00      1.00       890

   micro avg       0.95      0.97      0.96      3041
   macro avg       0.95      0.97      0.96      3041
weighted avg       0.96      0.97      0.96      3041
 samples avg       0.67      0.68      0.67      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [12]:
# Performance Summary without  adding I0=Ia+Ib+Ic as a feature
print("=== Baseline Results on Raw Inputs (Without I0) ===")
print(f"1. Random Forest Accuracy:      {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"2. XGBoost Accuracy:            {accuracy_score(y_test, y_pred_xgb):.4f}")
print(f"3. Voting Classifier Accuracy: {accuracy_score(y_test, y_pred_voting):.4f}")

=== Baseline Results on Raw Inputs (Without I0) ===
1. Random Forest Accuracy:      0.8881
2. XGBoost Accuracy:            0.8385
3. Voting Classifier Accuracy: 0.8506

ADDING I0 and V0 (Zero-Sequence-urrent and Zero-Sequence-Voltage)

In [16]:
#now let's add I0=Ia+Ib+Ic and V0=Va+Vb+Vc as features and retrain the models
df['I0'] = df['Ia'] + df['Ib'] + df['Ic']
df['V0'] = df['Va'] + df['Vb'] + df['Vc']

In [17]:
new_X = df[['Ia','Ib','Ic','Va','Vb','Vc','I0','V0']]
new_X

,Ia,Ib,Ic,Va,Vb,Vc,I0,V0
0,-151.291812,-9.677452,85.800162,0.400750,-0.132935,-0.267815,-75.169102,1.000000e-09
1,-336.186183,-76.283262,18.328897,0.312732,-0.123633,-0.189099,-394.140548,-1.000000e-09
2,-502.891583,-174.648023,-80.924663,0.265728,-0.114301,-0.151428,-758.464270,2.775558e-17
3,-593.941905,-217.703359,-124.891924,0.235511,-0.104940,-0.130570,-936.537188,0.000000e+00
4,-643.663617,-224.159427,-132.282815,0.209537,-0.095554,-0.113983,-1000.105860,0.000000e+00
...,...,...,...,...,...,...,...,...
7856,-66.237921,38.457041,24.912239,0.094421,-0.552019,0.457598,-2.868640,0.000000e+00
7857,-65.849493,37.465454,25.515675,0.103778,-0.555186,0.451407,-2.868364,0.000000e+00
7858,-65.446698,36.472055,26.106554,0.113107,-0.558211,0.445104,-2.868089,1.000000e-09
7859,-65.029633,35.477088,26.684731,0.122404,-0.561094,0.438690,-2.867813,0.000000e+00
7860,-64.598401,34.480799,27.250065,0.131669,-0.563835,0.432166,-2.867538,5.551115e-17

In [18]:
# Split the dataset into training and testing sets
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(new_X, y, test_size=0.2, random_state=42)

In [19]:
#model :1 Random Forest Classifier with new features
rf_model_new = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model_new.fit(X_train_new, y_train_new)

RandomForestClassifier(random_state=42)

In [20]:
y_pred_rf_new = rf_model_new.predict(X_test_new)
print('random forest classifier with new features classification report:\n', classification_report(y_test_new, y_pred_rf_new))

random forest classifier with new features classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       691
           1       1.00      1.00      1.00       611
           2       1.00      1.00      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       1.00      1.00      1.00      3041
   macro avg       1.00      1.00      1.00      3041
weighted avg       1.00      1.00      1.00      3041
 samples avg       0.69      0.69      0.69      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [21]:
#model 2: XGBoost Classifier with new features
xgb_base_new = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
xgb_new = MultiOutputClassifier(xgb_base_new)
xgb_new.fit(X_train_new, y_train_new)

MultiOutputClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=None,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=True,
                                              eval_metric=None,
                                              feature_types=None,
                                              feature_weights=None, gamma=None,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=0.1, max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None, max_depth=6,
                                              max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=100, n_jobs=None,
                                              num_parallel_tree=None, ...))

In [22]:
y_pred_xgb_new = xgb_new.predict(X_test_new)
print('XGBoost classifier with new features classification report:\n', classification_report(y_test_new, y_pred_xgb_new))

XGBoost classifier with new features classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       691
           1       1.00      1.00      1.00       611
           2       1.00      0.99      1.00       849
           3       1.00      1.00      1.00       890

   micro avg       1.00      1.00      1.00      3041
   macro avg       1.00      1.00      1.00      3041
weighted avg       1.00      1.00      1.00      3041
 samples avg       0.69      0.69      0.69      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [23]:
#model 3 : Voting Classifier (Decision Tree + k-NN + Naive Bayes) with new features
dt_new = DecisionTreeClassifier(random_state=42)
knn_new = KNeighborsClassifier(n_neighbors=5)
gnb_new = GaussianNB()

voting_base_new = VotingClassifier(
    estimators=[('dt', dt_new), ('knn', knn_new), ('gnb', gnb_new)],
    voting='hard'
)
voting_new = MultiOutputClassifier(voting_base_new)
voting_new.fit(X_train_new, y_train_new)

MultiOutputClassifier(estimator=VotingClassifier(estimators=[('dt',
                                                              DecisionTreeClassifier(random_state=42)),
                                                             ('knn',
                                                              KNeighborsClassifier()),
                                                             ('gnb',
                                                              GaussianNB())]))

In [24]:
y_pred_voting_new=voting_new.predict(X_test_new)
print('Voting classifier with new features classification report:\n', classification_report(y_test_new, y_pred_voting_new))

Voting classifier with new features classification report:
               precision    recall  f1-score   support

           0       1.00      0.87      0.93       691
           1       1.00      0.98      0.99       611
           2       1.00      0.97      0.99       849
           3       1.00      0.99      1.00       890

   micro avg       1.00      0.96      0.98      3041
   macro avg       1.00      0.95      0.97      3041
weighted avg       1.00      0.96      0.98      3041
 samples avg       0.69      0.67      0.68      3041

/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/mo/Desktop/electrical_fault_detection/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in samples with no true nor predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [25]:
# Performance Summary with new features
print("=== Baseline Results With new Features (With I0,I1) ===")
print(f"1. Random Forest Accuracy:      {accuracy_score(y_test_new, y_pred_rf_new):.4f}")
print(f"2. XGBoost Accuracy:            {accuracy_score(y_test_new, y_pred_xgb_new):.4f}")
print(f"3. Voting Classifier Accuracy: {accuracy_score(y_test, y_pred_voting_new):.4f}")

=== Baseline Results With new Features (With I0,I1) ===
1. Random Forest Accuracy:      0.9975
2. XGBoost Accuracy:            0.9949
3. Voting Classifier Accuracy: 0.9205

In [ ]:
#Saving the model
import joblib


#  Package model along with feature column names
model_payload = {
    'model': rf_model_new,
    'features': list(X_train_new.columns),
    'targets': list(y_train_new.columns)
}

# 3. Save to disk
model_filename = 'electrical_fault_classifier.joblib'
joblib.dump(model_payload, model_filename)

print(f"Model and metadata successfully saved to '{model_filename}'!")

Model and metadata successfully saved to 'electrical_fault_classifier.joblib'!